# Workflow for auto-assigning issues/PRs to Projects
name: Auto Assign to Project

on:
  pull_request:
#     branches: [main]
#     types: [opened, edited]
  issues:
    types: [opened]

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  assign_issues:
    if: ${{ github.event_name == 'issues' }}
    runs-on: ubuntu-latest
    name: Assign issues to project
    steps:
    - name: Assign new issues
      uses: srggrs/assign-one-project-github-action@1.2.0
      with:
        project: https://github.com/${{ github.repository }}/projects/1

  assign_prs:
    if: ${{ github.event_name == 'pull_request'}}
    runs-on: ubuntu-latest
    name: Assign pull requests to project
    steps:
    - name: Assign dependabot pull requests
      if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
      uses: srggrs/assign-one-project-github-action@1.2.0
      with:
        project: https://github.com/${{ github.repository }}/projects/1
        column_name: Dependabot Updates
    - name: Assign other pull requests
      if: ${{ github.event.pull_request.user.login != 'dependabot[bot]' }}
      uses: srggrs/assign-one-project-github-action@1.2.0
      with:
        project: https://github.com/${{ github.repository }}/projects/1
